### ISSUE TITLE
Broken/Unsupported Providers

### ISSUE THREAD

**Issue by billtomczak** [mpratt/Embera#78]
This is more a heads up than anything else.

* Hulu - no longer supports oembed
* Meetup - not clear but it looks like they don't support oembed anymore
* Sketchfab - we couldn't figure out how to get it working. The validateUrl method doesn't seem to be correct.
* Twitch - oembed support is unclear. We couldn't figure out how to get it to work
* Wordpress - we couldn't understand how or what this would be used for. Unable to find a sample url that works

We're just ignoring these in our implementation, so it's not a big deal.

**Comment by mpratt** [comment]
Hi @billtomczak 
Thanks for the info. I already knew about Hulu and Twitch. I just comitted a new update where I cleaned a little the provider list.

However, Meetup seems to be working on my end. The html response is not an Iframe, but raw html. Take this oembed response for example: https://api.meetup.com/oembed?format=json&url=https://www.meetup.com/kubernetes-Bogota-Group/events/274276177

Sketchfab is also working for me: https://sketchfab.com/oembed?format=json&url=https://sketchfab.com/3d-models/gothic-building-for-aria-pack-10-4c00c5e9a9a14388bd58ab9f87f0637b 
The thing with Sketchfab is that you need the direct link in order to embed it. You get it from the address bar of your browser.

And Finally, Wordpress, I need to think about it, since it technically works, but someone has a Blog on the wordpress.com plataform and is using a custom domain, the provider is not going to work. The user has to extend the wordpress provider and add it's own host and register it on the ProviderCollection and then inject it into Embera... That seems a little too complicated for something that should be simple..

Perhaps adding a new method like `Wordpress::registerHost('rarasaur.com');` could query the service as in: https://public-api.wordpress.com/oembed/?url=https://rarasaur.com/2020/08/01/g2-how-to-heal/&for=embera

**Comment by mpratt** [comment]
Yeah, I just pushed a new update that allows adding new hosts to a single provider on the fly. By doing this, the wordpress provider allows stuff like this.

```php
use Embera\Embera;
use Embera\Provider\Wordpress;

Wordpress::addHost('rarasaur.com');
$embera = new Embera();
echo $embera->autoEmbed('https://rarasaur.com/2020/08/01/g2-how-to-heal/');
```
Since I'm looking into a new way to generate automatically the provider documentation, I'll be adding This info once I'ts done.

**Comment by billtomczak** [comment]
Thanks Michael;

I can confirm the meetup link works. Guess I just didn't have a meetup page that could be accessed via oembed.

Using the link you provided for Sketchfab still doesn't work for me. Gives me a 404 not found response

I'll look into the Wordpress update. That would definitely make that provider more useful.
